version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: lumina-mysql
    environment:
      MYSQL_ROOT_PASSWORD: lumina
      MYSQL_DATABASE: lumina
    ports:
      - "3306:3306"
    volumes:
      - limina-mysql-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: lumina
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/lumina?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: lumina
      SPRING_DATASOURCE_PASSWORD: lumina
      SPRING_DATA_REDIS_HOST: 127.0.0.1
      SPRING_DATA_REDIS_PORT: 6379
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  limina-mysql-data:
